name: toptimer
description: Timer for everything

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.2
  dio: ^4.0.6
  flutter_screenutil: ^5.6.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  gap: ^2.0.1
  easy_localization: ^3.0.1
  transparent_image: ^2.0.1

cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.2.0
  google_fonts: ^4.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/

